# .github/workflows/sync-stock.yml
name: Sync WooCommerce Stock

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: package.json

      - name: Install dependencies
        run: npm install

      - name: Run stock sync
        env:
          WOOCOMMERCE_API_URL: ${{ secrets.WOOCOMMERCE_API_URL }}
          WOOCOMMERCE_CONSUMER_KEY: ${{ secrets.WOOCOMMERCE_CONSUMER_KEY }}
          WOOCOMMERCE_CONSUMER_SECRET: ${{ secrets.WOOCOMMERCE_CONSUMER_SECRET }}
          # override if you used a different meta key than `warde_url`:
          # WARD_URL_META_KEY: your_meta_key
        run: npm run sync
